site_name: Taikun
site_url: http://185.22.98.224
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css


theme:
    name: material
    favicon: https://cloud.tcpro.cz:30100/swift/v1/KEY_c5d050a1634d4ed1984f3844813f1a1d/general/Itera_logo.png
    logo: https://cloud.tcpro.cz:30100/swift/v1/KEY_121daf025c5742a6844217e262243c65/doc/taikun_icon_white.png
    features:
      - navigation.instant
      - navigation.tabs
      - toc.integrate
      - navigation.expand
      - navigation.sections
      - search.highlight
      - search.share
      - search.suggest
      - navigation.top
      - navigation.tracking
      - navigation.indexes
      - content.code.annotate
    palette:
      primary: pink

repo_url: https://github.com/itera-io/taikun-documentation
repo_name: Taikun Documentation

# Page tree
nav:
  - Home: index.md
  - First Steps: first-steps.md
  - Guidelines:
    - Login: guidelines/login.md
    - Change e-mail and password: guidelines/change-mail-password.md
    - Add cloud credentials: guidelines/add-cloud-credentials.md
    - Creating Profiles: guidelines/creating-profiles.md
    - Creating Cluster: guidelines/creating-a-cluster.md
    - Kubeconfigs, Backup, Monitoring, Lock, Reboot: guidelines/backup-monitoring-lock-reboot.md
    - Terraform Provider: guidelines/terraform-provider.md
    - Taikun-CLI: guidelines/taikun-cli.md
  - User: 
    - User: user/README.md
    - Login: user/login.md
    - Dashboard:
      - user/dashboard/README.md
      - Users: user/dashboard/users.md
      - Charts: user/dashboard/charts.md
      - Tables: user/dashboard/tables.md
    - Projects: 
      - user/projects/README.md
      - Project Details-K8s: user/projects/project-details-k8s.md
      - Project Details-VMs: user/projects/project-details-vms.md  
      - Kubernetes: user/projects/kubernetes.md
    - My Profie: user/my-profile.md
  - Manager:
    - Manager: manager/README.md
    - Login: manager/login.md
    - Dashboard:
      - manager/dashboard/README.md
      - Users: manager/dashboard/users.md
      - Charts: manager/dashboard/charts.md
      - Tables: manager/dashboard/tables.md
    - Projects:
      - manager/projects/README.md
      - Project Details-K8s: manager/projects/project-details-k8s.md
      - Project Details-VMs: manager/projects/project-details-vms.md
      - Kubernetes: manager/projects/kubernetes.md
      - Create a New Project: manager/projects/creating-a-new-project.md
    - Flavor Info: manager/flavor-info.md
    - Images: manager/images.md
    - Audit Log: manager/audit-log.md
    - Users: manager/users.md
    - Project Quotas: manager/project-quotas.md
    - Servers: manager/servers.md
    - Taikun Requests: manager/taikun-requests.md
    - Showback Rules: manager/showback-rules.md
    - Showback Summary: manager/showback-summary.md
    - Ticketing: manager/ticketing.md
    - Standalone VMs: manager/standalone-vms.md
    - Chargeback: manager/chargeback.md
    - Usage Reports: manager/usage-reports.md
    - Cloud Credentials: manager/cloud-credentials.md
    - Backup Credentials: manager/backup-credentials.md
    - Showback Credentials: manager/showback-credentials.md
    - Kubernetes Profiles: manager/kubernetes-profiles.md
    - Access Profiles: manager/access-profiles.md
    - Alerting Profiles: manager/alerting-profiles.md
    - Policy Profiles: manager/policy-profiles.md
    - Standalone Profiles: manager/standalone-profiles.md
    - Slack Configuration: manager/slack-configuration.md
    - My Profile: manager/my-profile.md
  - Partner:
    - Partner: partner/README.md
    - Login: partner/login.md
    - Dashboard:
       - partner/dashboard/README.md
       - Select Organization: partner/dashboard/select-organization.md
       - Users: partner/dashboard/users.md
       - Charts: partner/dashboard/charts.md
       - Tables: partner/dashboard/tables.md
    - Projects:
       - partner/projects/README.md
       - Projects Details-K8s: partner/projects/project-details-k8s.md
       - Projects Details-VMs: partner/projects/project-details-vms.md
       - Kubernetes: partner/projects/kubernetes.md
       - Create a New Project: partner/projects/creating-a-new-project.md
    - Flavor Info: partner/flavor-info.md
    - Images: partner/images.md
    - Audit Log: partner/audit-log.md
    - Users: partner/users.md
    - Project Quotas: partner/project-quotas.md
    - Servers: partner/servers.md
    - Taikun Requests: partner/taikun-requests.md
    - Showback Rules: partner/showback-rules.md
    - Showback Summary: partner/showback-summary.md
    - Ticketing: partner/ticketing.md
    - Standalone VMs: partner/standalone-vms.md
    - Chargeback: partner/chargeback.md
    - Usage Reports: partner/usage-reports.md
    - Cloud Credentials: partner/cloud-credentials.md
    - Backup Credentials: partner/backup-credentials.md
    - Billing Credentials: partner/billing-credentials.md
    - Showback Credentials: partner/showback-credentials.md
    - Kubernetes Profiles: partner/kubernetes-profiles.md
    - Access Profiles: partner/access-profiles.md
    - Alerting Profiles: partner/alerting-profiles.md
    - Policy Profiles: partner/policy-profiles.md
    - Standalone Profiles: partner/standalone-profiles.md
    - Organizations: partner/organizations.md
    - Billing Rules: partner/billing-rules.md
    - Slack Configuration: partner/slack-configuration.md
    - My Profile: partner/my-profile.md
  - Tech Book:
    - LoadBalancer: tech-book/loadbalancers.md
  - Dictionary:
    - From A to Z: dictionary/from-a-to-z.md
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iteraio
      name: itera.io on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/itera-io
      name: itera.io on Linkedln
  generator: false
copyright: Copyright &copy; 2022 - Itera.io
